import Head from "next/head";
import Navbar from "../components/Navbar";
import Wrapper from "../components/Wrapper";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Wrapper posts={posts} />
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:5000/api/post`);
  const posts = await res.json();

  if (!posts) {
    return {
      notFound: true,
    };
  }

  return {
    props: { posts }, // will be passed to the page component as props
  };
}
